# Generated by Django 3.1.7 on 2022-03-31 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentTracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='sport',
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(related_name='team', to='TournamentTracker.Player'),
        ),
        migrations.AlterField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='TournamentTracker.tournament'),
        ),
        migrations.CreateModel(
            name='TempPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('team_num', models.PositiveSmallIntegerField(default=0)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='TournamentTracker.category')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TournamentTracker.school')),
                ('tournament', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tournament_teams', to='TournamentTracker.tournament')),
            ],
        ),
    ]
