# Generated by Django 3.1.7 on 2022-03-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentTracker', '0002_auto_20220331_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_num',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
