# Generated by Django 3.1.7 on 2022-03-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentTracker', '0003_team_team_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_num',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
