# Generated by Django 3.1.7 on 2022-04-07 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentTracker', '0004_auto_20220331_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tournament_teams', to='TournamentTracker.tournament'),
        ),
        migrations.AlterField(
            model_name='tempplayer',
            name='tournament',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='TournamentTracker.tournament'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='schools',
            field=models.ManyToManyField(blank=True, related_name='tournaments', to='TournamentTracker.School'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(blank=True, choices=[('Not Started', 'Not Started'), ('Ongoing', 'Ongoing'), ('Ended', 'Ended')], default='Not Started', max_length=16, null=True),
        ),
    ]
