# Generated by Django 3.1.7 on 2022-04-10 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentTracker', '0005_auto_20220408_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_matches', to='TournamentTracker.category'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1_match', to='TournamentTracker.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2_match', to='TournamentTracker.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_matches', to='TournamentTracker.tournament'),
        ),
    ]
