# Generated by Django 3.1.7 on 2022-04-19 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentTracker', '0007_auto_20220412_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='played_by',
            field=models.ManyToManyField(blank=True, related_name='matches_played', to='TournamentTracker.Player'),
        ),
        migrations.AddField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('Starting', 'Starting'), ('Substitute', 'Substitute')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='tempplayer',
            name='role',
            field=models.CharField(choices=[('Starting', 'Starting'), ('Substitute', 'Substitute')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='tempplayer',
            name='tournament',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='temp_players', to='TournamentTracker.tournament'),
        ),
    ]
