# Generated by Django 3.1.7 on 2022-04-20 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentTracker', '0008_auto_20220420_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='played_by',
        ),
    ]
