# Generated by Django 3.1.7 on 2022-04-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentTracker', '0009_remove_match_played_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='played_by',
            field=models.ManyToManyField(blank=True, related_name='matches_played', to='TournamentTracker.Player'),
        ),
    ]
