# Generated by Django 4.0.4 on 2022-12-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentTracker', '0013_alter_tournament_options_tournament_sets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='sets',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
